/* Generated By:JavaCC: Do not edit this line. ToyParserTreeConstants.java Version 5.0 */
public interface ToyParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTVOID = 1;
  public int JJTSPECIALBLOCK = 2;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "void",
    "SpecialBlock",
  };
}
/* JavaCC - OriginalChecksum=d8217a882ae1a4d4652f6424972ba256 (do not edit this line) */
